In [3]:
colors = ['red','green','yellow','purple']
for i in range (len(colors)-1,-1,-1):
    print(colors[i],end=" ")
    

purple yellow green red 

In [2]:
colors = ['red','green','yellow','purple']

for color in reversed (colors):
    print(colors,end=" ")    

['red', 'green', 'yellow', 'purple'] ['red', 'green', 'yellow', 'purple'] ['red', 'green', 'yellow', 'purple'] ['red', 'green', 'yellow', 'purple'] 

dt = {'id' : [11,12,13,14,15]}
      ' first_name' : ['A','B','C','D','E']
      ' 'company' : ['aa','bb','cc','dd','ee']

## numpy package
   ### numpy is a bit like python list
   ### numpy is also one of the data structure 
   ### numpy is short name for "numeric python" or "numerical python"

In [3]:
import numpy as np

In [4]:
li={1,2,3,4,5}
print(li,end=" ")

{1, 2, 3, 4, 5} 

In [5]:
array = np.array(li)
print (array)

{1, 2, 3, 4, 5}


In [12]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [16]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.hstack((a1,a2)))

a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
